V3.5 updates
workarea-commerce/workarea-yotpo pull request #1
Opened 2019-11-11 21:32 UTC by jyucis

no changelog

YOTPO-1

2019-11-11 21:47 UTC, tubbo requested changes

2019-11-11 21:47 UTC, tubbo commented on .github/workflows/ci.yml
> +    - uses: workarea-commerce/ci/eslint@v1
idk if you really need this since there's no JS in this repo...

2019-11-12 14:01 UTC, bencrouse requested changes
Can we get that rubocop all patched up?

2019-11-18 13:35 UTC, bencrouse approved these changes

2019-11-18 13:36 UTC, merged